spring:
  datasource:
    password: 123456
    username: root
    url: jdbc:mysql:///linlizuzu?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    database: 0
    host: localhost
    port: 6379
server:
  port: 8055

